---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hello
  name: hello
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: hello
    spec:
      containers:
      - image: nginx:1.13.7
        imagePullPolicy: IfNotPresent
        name: hello
        ports:
        - containerPort: 80
          protocol: TCP
